### PR TITLE
add docs for css font loading api

### LINKED ISSUE #2: Implement documentation on font loading using css font loading api.
Implement font selection using CSS font loading API and a CSS font loading API polyfill using @font-face and offscreen text to force loading the fonts.

### PR DESCRIPTION
**Pull request by sachinraja**
closes #2

### CODE REVIEW

**Review by ILOVEPIE — COMMENTED** [review]
Would you be able to regenerate the README.md?

**Comment by sachinraja** [comment]
I did regenerate the README

**Comment by ILOVEPIE** [comment]
> I did regenerate the README

sorry didn't see that

**Review by ILOVEPIE — APPROVED** [review]
LGTM

**Pull request merged**
